### ISSUE TITLE
external CC image is gone

### ISSUE THREAD

**Issue by j12i** [audiodude/songs.travisbriggs.com#11]
https://github.com/audiodude/songs.travisbriggs.com/blob/51bfe8c8a6f812d989471e23df5c32f99ed3a897/templates/base.html#L31

**Comment by j12i** [comment]
Ok, it's not, but my browser didn't want to load it into the site...

**Comment by audiodude** [comment]
Okay glad it worked eventually!

**Comment by j12i** [comment]
No, it doesn't. The CC site sets some header that tells my browser not to load their stuff into other sites, and Vivaldi obeys.

**Comment by audiodude** [comment]
Just checked the code, and I'm not setting any strange looking attributes on the image tag. Is it a CORS issue?

**Comment by j12i** [comment]
I just found out the problem is totally on my end. I'm using EFF's Privacy Badger, and that "learned" to consider i.creativecommons.org a tracker. Just because it's embedded on lots of sites I suppose.

Sorry for the noise.

**Comment by audiodude** [comment]
Interesting! Glad you got it figured out.
